### ISSUE TITLE
Mod not working

### ISSUE THREAD

**Issue by MusicalCookie** [Leo3418/HBWHelper#1]
## Platform Information

- HBW Helper version:
- Minecraft version:
- Minecraft Forge version:
- Java version: 
- Operating system:
- Other mods you have installed:

## Additional Information

```
(Please paste any error log or crash report here so that it is more readable)
```

**Comment by Leo3418** [comment]
The mod will only show its GUI when you are playing in Hypixel Bed Wars. Can you enter a Bed Wars game and check again?

**Comment by MusicalCookie** [comment]
I entered a game and still nothing, i'll check again however.

**Comment by Leo3418** [comment]
Thanks for your reply. I am looking forward to your report.

**Comment by MusicalCookie** [comment]
I just played a game of bedwars, and throughout the game I diddn't notice any changes.

**Comment by Leo3418** [comment]
Thanks for your report. You should have seen an issue template when you were opening this ticket, but you overwrote it for some reason. The current information you provided is not enough for me to confirm this issue, so please fill out the issue template and include as many details as you can provide. I have modified your original post to the template, so you can directly work on it.

To help us resolve issues quickly, please follow the template in the future. You should also read the [Issue Guidelines](https://github.com/Leo3418/HBWHelper/blob/dev/CONTRIBUTING.md#issue-guidelines) for hints on making your issue report more detailed.

**Comment by Leo3418** [comment]
Because you have not responded to the request for a week, and I could not obtain more information about this problem, the issue is being closed. If you would like to provide more information at any time, please do not hesitate to post it here, and I will reopen this issue and continue to work on it.
